AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Sample SAM Template

Resources:
  ApplesApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      DefinitionUri: ./swagger.yaml
      Variables:
        ListApplesFunction: !Ref ListApples

  ListApples:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/list.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        ListApples:
          Type: Api
          Properties:
            RestApiId: !Ref ApplesApiGateway
            Path: /apples
            Method: get

Outputs:
  ListApplesApi:
    Description: "API Gateway endpoint URL for live stage for ListApples function"
    Value: !Join ['', ['https://', !Ref ApplesApiGateway, '.execute-api.', !Ref 'AWS::Region',  '.amazonaws.com/live/apples' ] ]

  ListApplesFunction:
    Description: "ListApples Lambda Function ARN"
    Value: !GetAtt ListApples.Arn
