AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Sample SAM Template

Parameters:
  DynamoDBTableName:
    Type: String
    Default: ApplesTable

Resources:
  DynamoApplesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
      - AttributeName: Location
        AttributeType: S
      - AttributeName: AppleId
        AttributeType: S
      KeySchema:
      - AttributeName: Location
        KeyType: HASH
      - AttributeName: AppleId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ApplesApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      DefinitionUri: ./swagger.yaml
      Variables:
        ListApplesFunction: !Ref ListApples

  ListApples:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/list.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      Events:
        ListApples:
          Type: Api
          Properties:
            RestApiId: !Ref ApplesApiGateway
            Path: /apples
            Method: get

Outputs:
  ListApplesApi:
    Description: "API Gateway endpoint URL for live stage for ListApples function"
    Value: !Join ['', ['https://', !Ref ApplesApiGateway, '.execute-api.', !Ref 'AWS::Region',  '.amazonaws.com/live/apples' ] ]

  ListApplesFunction:
    Description: "ListApples Lambda Function ARN"
    Value: !GetAtt ListApples.Arn
