AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Sample SAM Template

Resources:
  ListApples:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/list.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        ListApples:
          Type: Api
          Properties:
            Path: /apples
            Method: get

Outputs:
    ListApplesApi:
      Description: "API Gateway endpoint URL for Prod stage for ListApples function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/apples/"

    ListApplesFunction:
      Description: "ListApples Lambda Function ARN"
      Value: !GetAtt ListApples.Arn
